/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OurWorkRouteImport } from './routes/our-work'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TeamRouteImport } from './routes/team'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminMenusRouteImport } from './routes/_authenticated/admin.menus'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSlidesRouteImport } from './routes/_authenticated/admin.slides'
import { Route as AuthenticatedAdminPagesIndexRouteImport } from './routes/_authenticated/admin.pages.index'
import { Route as AuthenticatedAdminPagesSlugRouteImport } from './routes/_authenticated/admin.pages.$slug'
import { Route as AuthenticatedAdminPostsIndexRouteImport } from './routes/_authenticated/admin.posts.index'
import { Route as AuthenticatedAdminPostsIdRouteImport } from './routes/_authenticated/admin.posts.$id'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkRoute = OurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMenusRoute = AuthenticatedAdminMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSlidesRoute =
  AuthenticatedAdminSlidesRouteImport.update({
    id: '/slides',
    path: '/slides',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesIndexRoute =
  AuthenticatedAdminPagesIndexRouteImport.update({
    id: '/pages/',
    path: '/pages/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesSlugRoute =
  AuthenticatedAdminPagesSlugRouteImport.update({
    id: '/pages/$slug',
    path: '/pages/$slug',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPostsIndexRoute =
  AuthenticatedAdminPostsIndexRouteImport.update({
    id: '/posts/',
    path: '/posts/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPostsIdRoute =
  AuthenticatedAdminPostsIdRouteImport.update({
    id: '/posts/$id',
    path: '/posts/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/mcp': typeof McpRoute
  '/our-work': typeof OurWorkRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/menus': typeof AuthenticatedAdminMenusRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/slides': typeof AuthenticatedAdminSlidesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/pages/$slug': typeof AuthenticatedAdminPagesSlugRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/pages/': typeof AuthenticatedAdminPagesIndexRoute
  '/admin/posts/': typeof AuthenticatedAdminPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/mcp': typeof McpRoute
  '/our-work': typeof OurWorkRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/menus': typeof AuthenticatedAdminMenusRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/slides': typeof AuthenticatedAdminSlidesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/pages/$slug': typeof AuthenticatedAdminPagesSlugRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/pages': typeof AuthenticatedAdminPagesIndexRoute
  '/admin/posts': typeof AuthenticatedAdminPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/mcp': typeof McpRoute
  '/our-work': typeof OurWorkRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/menus': typeof AuthenticatedAdminMenusRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/slides': typeof AuthenticatedAdminSlidesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/pages/$slug': typeof AuthenticatedAdminPagesSlugRoute
  '/_authenticated/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/admin/pages/': typeof AuthenticatedAdminPagesIndexRoute
  '/_authenticated/admin/posts/': typeof AuthenticatedAdminPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/get-involved'
    | '/impact'
    | '/mcp'
    | '/our-work'
    | '/resources'
    | '/team'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/blog/$slug'
    | '/blog/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/media'
    | '/admin/menus'
    | '/admin/settings'
    | '/admin/slides'
    | '/admin/'
    | '/admin/pages/$slug'
    | '/admin/posts/$id'
    | '/api/public/media/$'
    | '/lovable/email/transactional/preview'
    | '/admin/pages/'
    | '/admin/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/get-involved'
    | '/impact'
    | '/mcp'
    | '/our-work'
    | '/resources'
    | '/team'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/blog'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/media'
    | '/admin/menus'
    | '/admin/settings'
    | '/admin/slides'
    | '/admin'
    | '/admin/pages/$slug'
    | '/admin/posts/$id'
    | '/api/public/media/$'
    | '/lovable/email/transactional/preview'
    | '/admin/pages'
    | '/admin/posts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/get-involved'
    | '/impact'
    | '/mcp'
    | '/our-work'
    | '/resources'
    | '/team'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/blog/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/menus'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/slides'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/pages/$slug'
    | '/_authenticated/admin/posts/$id'
    | '/api/public/media/$'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/admin/pages/'
    | '/_authenticated/admin/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  ImpactRoute: typeof ImpactRoute
  McpRoute: typeof McpRoute
  OurWorkRoute: typeof OurWorkRoute
  ResourcesRoute: typeof ResourcesRoute
  TeamRoute: typeof TeamRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work': {
      id: '/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OurWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/menus': {
      id: '/_authenticated/admin/menus'
      path: '/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AuthenticatedAdminMenusRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/slides': {
      id: '/_authenticated/admin/slides'
      path: '/slides'
      fullPath: '/admin/slides'
      preLoaderRoute: typeof AuthenticatedAdminSlidesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages/': {
      id: '/_authenticated/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AuthenticatedAdminPagesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages/$slug': {
      id: '/_authenticated/admin/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/admin/pages/$slug'
      preLoaderRoute: typeof AuthenticatedAdminPagesSlugRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/posts/': {
      id: '/_authenticated/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AuthenticatedAdminPostsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/posts/$id': {
      id: '/_authenticated/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AuthenticatedAdminPostsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminMenusRoute: typeof AuthenticatedAdminMenusRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSlidesRoute: typeof AuthenticatedAdminSlidesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPagesSlugRoute: typeof AuthenticatedAdminPagesSlugRoute
  AuthenticatedAdminPostsIdRoute: typeof AuthenticatedAdminPostsIdRoute
  AuthenticatedAdminPagesIndexRoute: typeof AuthenticatedAdminPagesIndexRoute
  AuthenticatedAdminPostsIndexRoute: typeof AuthenticatedAdminPostsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminMenusRoute: AuthenticatedAdminMenusRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSlidesRoute: AuthenticatedAdminSlidesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPagesSlugRoute: AuthenticatedAdminPagesSlugRoute,
  AuthenticatedAdminPostsIdRoute: AuthenticatedAdminPostsIdRoute,
  AuthenticatedAdminPagesIndexRoute: AuthenticatedAdminPagesIndexRoute,
  AuthenticatedAdminPostsIndexRoute: AuthenticatedAdminPostsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  ImpactRoute: ImpactRoute,
  McpRoute: McpRoute,
  OurWorkRoute: OurWorkRoute,
  ResourcesRoute: ResourcesRoute,
  TeamRoute: TeamRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
